Crystal/add bu base
bu-ist/responsive-foundation pull request #275
Opened 2024-12-13 21:05 UTC by crystalms

Add BU Base CSS variables to BURF base, theme and customizations.

This is just a first pass through and needs to be tested more against a sandbox to see if any of the variables need to be adjusted.

2025-02-10 19:20 UTC, acketon commented
@crystalms can you change the base branch on this to merge into `v6`? @timkingbu and I have created branches for each major version so we'll use that now instead of `feature/block-editor`

2025-03-07 19:31 UTC, acketon requested changes
This looks good. Now that bu-base has been pushed to NPM can you remove it from yalc in this PR and load it from NPM instead? After that I think this is good to merge though we'll have to see if there are conflicts with Charlie's changes too.

2025-05-14 21:21 UTC, acketon approved these changes
These look great. Pretty much everything makes sense to me based on my limited experience with custom properties. 👍

2025-05-14 21:21 UTC, acketon commented on burf-base/_forms.scss
>  %button-styles {
just a thought unrelated to this PR. I've never really liked having the button styles in the _forms.scss partial. Yes buttons are used in a form, but they are more than that. Up to the rest of y'all but I'd be in favor of moving any button related styles to their own partial.

2025-05-14 21:21 UTC, acketon commented on burf-base/burf-base.scss
> +@forward "../.yalc/@bostonuniversity/base/styles/base/primitive";
I'm assuming this needs to be updated with a different path without yalc?

2025-05-14 21:21 UTC, acketon commented on burf-base/grid/_grid-placeholders.scss
> +	margin-left: -$grid-margin-width * 1%;
Is this output the same value? I'm assuming it's a change due to the move to Dart Sass?

2025-05-14 21:21 UTC, acketon commented on burf-theme/content/_galleries.scss
> +	border-right: var(--gallery-margin, #{$margin-gallery}) solid transparent;
margin for the border? I see the foundation variables did that though.

2025-05-14 21:21 UTC, acketon commented on burf-theme/content/_galleries.scss
> +	border-right: var(--gallery-margin, #{$margin-gallery}) solid transparent;
ah I see the gallery uses transparent borders for the layout? That seems like something we should change in the new theme framework.

2025-05-14 21:21 UTC, acketon commented on burf-theme/layout/_footer.scss
>  }
Hmm, does this even make sense here in the _footer.scss partial?

2025-05-15 14:30 UTC, crystalms commented on burf-base/_forms.scss
>  %button-styles {
Yes please!!!! I'm 100% on board with that, and I think every designer I've talked to agrees haha.

2025-05-15 14:32 UTC, crystalms commented on burf-base/grid/_grid-placeholders.scss
> +	margin-left: -$grid-margin-width * 1%;
Correct! It was breaking in Dart Sass, since it was just appending the % as a string not actually making the number a percent and making it invalid. The correct/recommended way now is to multiply it by 1% in order to turn it into a percentage.

2025-05-15 19:34 UTC, crystalms commented on burf-base/burf-base.scss
> +@forward "../.yalc/@bostonuniversity/base/styles/base/primitive";
I just deleted this--I think this was an older instance when I was testing that needed to be removed.

2025-05-15 20:00 UTC, merged